# Site settings
author: Dustin Arceneaux
title: Flatiron Full Time
header-img: img/home-bg.png
email: djarcene@gmail.com
copyright_name: Dustin Arceneaux
description: > # this means to ignore newlines until "baseurl:"
  Dustin's Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dja173

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
